Changed UI
Suryansh1720001/Taaveez pull request #52
Opened 2023-06-02 15:50 UTC by AryanShivva

changed the ui of the onetime intro page into a nice design and also changed the splashscreen of the app.

## Fixes Issue
#51 

## Changes proposed
Succesfully changed the splash screen UI of the app.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

<img width="359" alt="Screenshot 2023-05-31 at 11 43 17 PM" src="https://github.com/Suryansh1720001/Taaveez/assets/124916476/f2a23b4d-42fa-46c5-8e2f-fd23e5ceae05">

## Note to reviewers

2023-06-06 06:04 UTC, Suryansh1720001 commented
Could you please provide me with the demo video of the application?

2023-06-07 04:25 UTC, Suryansh1720001 commented
@AryanShivva,

Please rename the images based on their usage:

1. Kindly rename this drawable image appropriately.

![image](https://github.com/Suryansh1720001/Taaveez/assets/85965606/7c11d08d-d29b-4243-b71b-9623cff1d59b)

---

2. Please note that this image contains a Canva watermark, which is not acceptable. Ensure that the image is free from any watermarks before using it.

![image](https://github.com/Suryansh1720001/Taaveez/assets/85965606/59a0b69b-b1cc-407c-8b60-a401a2038ad4)

Furthermore, once you have successfully resolved these issues, please send the pull request (PR) in a single commit by squashing them.

2023-06-08 11:39 UTC, Suryansh1720001 commented
@AryanShivva 
Any Update?

2023-06-09 02:51 UTC, itssuryansh1 requested changes
remove watermark

2023-06-14 06:41 UTC, Vaibhav2002 commented on app/src/main/res/drawable/new_backround_aryan.xml
> +<?xml version="1.0" encoding="utf-8"?>
can you rename this file to 'background`?

2023-06-14 06:44 UTC, Vaibhav2002 commented
> @AryanShivva Could you please provide me with the demo video of the application?

@AryanShivva please upload this.

2023-06-15 13:46 UTC, AryanShivva commented
https://github.com/Taaveez/Taaveez-android/assets/124916476/33ff6aa0-2d74-4bbf-b4e4-750936565315

2023-06-15 17:04 UTC, Vaibhav2002 commented
> 
> https://github.com/Taaveez/Taaveez-android/assets/124916476/33ff6aa0-2d74-4bbf-b4e4-750936565315
> 
> 

Why isn't the splash screen shown the first time?

2023-06-17 11:23 UTC, AryanShivva commented
According to the code already written the splash screen will not appear for the first time when we are opening the app.One time Activity screen will directly appear for the first time.

2023-06-19 12:32 UTC, Suryansh1720001 commented
@AryanShivva 
Please rename the file "new_background.xml" and remove any mention of your name. Additionally, to avoid copyright issues, please ensure that any images used are free of restrictions or consider using a paid image.


---
Could you please provide a different image or use a paid version of the image? The current image you shared still has visible watermark signs. Thank you.

<img src ="https://github.com/Taaveez/Taaveez-android/assets/85965606/6b7047c5-7684-47ff-b74e-72a91ba211eb" width="500" heigth="500">

2023-06-20 06:48 UTC, Vaibhav2002 commented
> According to the code already written the splash screen will not appear for the first time when we are opening the app.One time Activity screen will directly appear for the first time.

Hi @AryanShivva this is kinda wrong UI, because Splash Screen should be shown each and every time. 
Please update the code to show Splash Screen every time.

2024-01-12 07:22 UTC, Suryansh1720001 commented
no response

2024-01-12 07:22 UTC, closed without merging